### ISSUE TITLE
std::variant performance issues

### ISSUE THREAD

**Issue by vtyulb** [jimporter/bencode.hpp#5]
Hi, @jimporter!

Congrats on v1.0.0 release!

In this release you have added this note:
`if Boost is installed, bencode.hpp will provide the ability to use [boost::variant](https://github.com/jimporter/bencode.hpp#boostvariant), which can perform significantly better than std::variant on some data sets (up to 2x faster than libstdc++ or libc++ when decoding integers)
`

Could you please clarify why you think that boost::variant outperforms std::variant?

I wrote simple benchmark to test it out: https://gist.github.com/vtyulb/6c0a7a553c3d9a6cdb74e1673b17f047
Benchmark shows no difference for a small bencode::dict encode & decode on amd ryzen 7 pro 4750u (archlinux / clang 15).

**Comment by jimporter** [comment]
> Could you please clarify why you think that boost::variant outperforms std::variant?

The `integers.bencode` dataset [here](https://github.com/fbdtemme/bencode/tree/main/benchmark/resources) showed that with `bencode.hpp`, using `boost::variant` was about twice as fast as  `std::variant`.

(Note: it's been a while since I've run these tests though, and I don't recall all the details.)

**Comment by vtyulb** [comment]
Thank you!
